'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw} from 'lucide-react';
import Nav from '@/components/Nav';
import StatCard from '@/components/StatCard';
import ClientStoriesPanel from '@/components/ClientStoriesPanel';
import AdminKycReviewPanel from '@/components/AdminKycReviewPanel';
import AdminOperationsPanel from '@/components/AdminOperationsPanel';
import AdminReceiptReviewPanel from '@/components/AdminReceiptReviewPanel';
import AdminProvidersPanel from '@/components/AdminProvidersPanel';

type Instrument={id:string;symbol:string;name:string;baseAsset:string;quoteAsset:string;price:number;leverage:number;makerFee:number;takerFee:number;enabled:boolean};
type LoginAuditEvent={id:string;action:string;createdAt:string;metadata:{clientIp?:string|null;userAgent?:string|null;authMethod?:string;reason?:string|null}|null};

export default function Admin(){
 const [stats,setStats]=useState<any>({}); const [users,setUsers]=useState<any[]>([]); const [funds,setFunds]=useState<any[]>([]); const [positions,setPositions]=useState<any[]>([]); const [settings,setSettings]=useState<any[]>([]); const [instruments,setInstruments]=useState<Instrument[]>([]); const [audit,setAudit]=useState<any[]>([]); const [msg,setMsg]=useState(''); const [fundingNotes,setFundingNotes]=useState<Record<string,string>>({});
 const [initialLoading,setInitialLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [loadError,setLoadError]=useState(''); const loadInFlight=useRef(false);
 const [expandedLoginUser,setExpandedLoginUser]=useState(''); const [loginHistory,setLoginHistory]=useState<Record<string,{loading:boolean;events:LoginAuditEvent[];error:string}>>({});
 const [newInstrument,setNewInstrument]=useState({symbol:'',name:'',baseAsset:'',quoteAsset:'USD',price:'1',leverage:'1',makerFee:'0.001',takerFee:'0.0015'});
 async function load(){
  if(loadInFlight.current)return;
  loadInFlight.current=true;setRefreshing(true);
  try{
   const responses=await Promise.all([fetch('/api/admin/stats'),fetch('/api/admin/users'),fetch('/api/admin/funding'),fetch('/api/admin/positions'),fetch('/api/admin/settings'),fetch('/api/admin/instruments'),fetch('/api/admin/audit')]);
   if(responses.some(response=>!response.ok))throw new Error('Unable to load all administrator data.');
   const [nextStats,nextUsers,nextFunds,nextPositions,nextSettings,nextInstruments,nextAudit]=await Promise.all(responses.map(response=>response.json()));
   setStats(nextStats);setUsers(nextUsers);setFunds(nextFunds);setPositions(nextPositions);setSettings(nextSettings);setInstruments(nextInstruments);setAudit(nextAudit);setLoadError('');
  }catch(exception){setLoadError(exception instanceof Error?exception.message:'Unable to load administrator data.')}
  finally{loadInFlight.current=false;setRefreshing(false);setInitialLoading(false)}
 }
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 async function toggleLoginHistory(userId:string){
  if(expandedLoginUser===userId){setExpandedLoginUser('');return;}
  setExpandedLoginUser(userId);
  if(loginHistory[userId])return;
  setLoginHistory(current=>({...current,[userId]:{loading:true,events:[],error:''}}));
  try{
   const response=await fetch(`/api/admin/audit?loginUserId=${encodeURIComponent(userId)}`,{cache:'no-store'});
   const result=await response.json();
   if(!response.ok)throw new Error(result.error||'Unable to load login history.');
   setLoginHistory(current=>({...current,[userId]:{loading:false,events:result,error:''}}));
  }catch{
   setLoginHistory(current=>({...current,[userId]:{loading:false,events:[],error:'Unable to load login history.'}}));
  }
 }
 async function userPatch(userId:string,field:string,value:string){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,[field]:value})});setMsg(r.ok?'User updated':'Update failed');load()}
 async function forceClose(positionId:string){const r=await fetch('/api/admin/positions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({positionId})});setMsg(r.ok?'Position closed':'Force close failed');load()}
 async function saveSetting(key:string,value:string){const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key,value})});setMsg(r.ok?'Setting saved':'Setting failed');load()}
 async function review(id:string,decision:string,note=''){const r=await fetch('/api/admin/funding',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,decision,note})});const j=await r.json();setMsg(r.ok?'Funding reviewed':j.error||'Review failed');load()}
 async function openFundingReceipt(id:string){try{const response=await fetch(`/api/admin/funding/${encodeURIComponent(id)}/receipt`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Receipt unavailable.');window.open(result.url,'_blank','noopener,noreferrer')}catch(error){setMsg(error instanceof Error?error.message:'Receipt unavailable.')}}
 async function instrumentPatch(id:string,data:Partial<Instrument>){const r=await fetch('/api/admin/instruments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...data})});setMsg(r.ok?'Instrument updated':(await r.json()).error||'Instrument update failed');load()}
 async function createInstrument(){const p={...newInstrument,price:Number(newInstrument.price),leverage:Number(newInstrument.leverage),makerFee:Number(newInstrument.makerFee),takerFee:Number(newInstrument.takerFee),enabled:true};const r=await fetch('/api/admin/instruments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const j=await r.json();setMsg(r.ok?'Instrument created':j.error||'Create failed');if(r.ok)setNewInstrument({symbol:'',name:'',baseAsset:'',quoteAsset:'USD',price:'1',leverage:'1',makerFee:'0.001',takerFee:'0.0015'});load()}
 return <><Nav/><main className="mx-auto max-w-7xl px-4 py-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="gold text-xs font-bold tracking-[.25em]">CONTROL CENTER</div><h1 className="text-3xl font-black">Aurevia administration</h1></div><div className="flex gap-2"><button className="btn min-h-11 bg-white/5" type="button" disabled={refreshing} aria-busy={refreshing} onClick={()=>void load()}><RefreshCw size={15}/>{refreshing?'Refreshing…':'Refresh data'}</button><a className="btn bg-white/5" href="/admin/login">Admin login</a></div></div>{msg&&<p className="mt-2 muted" role="status">{msg}</p>}
 {initialLoading&&<p className="mt-3 min-h-8 text-sm muted" role="status">Loading control center data…</p>}
 {loadError&&<div className="account-callout mt-3" role="alert"><span>{loadError}</span><button className="text-link" type="button" disabled={refreshing} onClick={()=>void load()}>Retry</button></div>}
 <nav className="my-4 flex gap-2 overflow-x-auto pb-1" aria-label="Admin operations sections"><a className="btn min-h-11 shrink-0 bg-white/5" href="#overview">Overview</a><a className="btn min-h-11 shrink-0 bg-white/5" href="#providers">Providers</a><a className="btn min-h-11 shrink-0 bg-white/5" href="#operations">Orders / Ledger</a><a className="btn min-h-11 shrink-0 bg-white/5" href="#kyc-verification">KYC review</a><a className="btn min-h-11 shrink-0 bg-white/5" href="#client-stories">Client stories</a><a className="btn min-h-11 shrink-0 bg-white/5" href="/admin/investments">Investment operations</a><a className="btn min-h-11 shrink-0 bg-white/5" href="/admin/payments">Payments</a><a className="btn min-h-11 shrink-0 bg-white/5" href="/admin/support">Nova support</a><a className="btn min-h-11 shrink-0 bg-white/5" href="/markets">Markets</a><a className="btn min-h-11 shrink-0 bg-white/5" href="/notifications">Notifications</a></nav>
 <ClientStoriesPanel/><AdminKycReviewPanel/><AdminProvidersPanel/><AdminOperationsPanel/><AdminReceiptReviewPanel/>
 <div id="overview" className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Users" value={String(stats.users??0)}/><StatCard label="DEMO users" value={String(stats.demoUsers??0)}/><StatCard label="REAL users" value={String(stats.realUsers??0)}/><StatCard label="Pending KYC" value={String(stats.pendingKyc??0)}/><StatCard label="Pending investments" value={String(stats.pendingInvestments??0)}/><StatCard label="Active / paused investments" value={String(stats.activeInvestments??0)}/><StatCard label="Open DEMO orders" value={String(stats.openOrders??0)}/><StatCard label="Enabled markets · feed" value={`${stats.enabledMarkets??0} · ${stats.marketDataMode||'unknown'}`}/><StatCard label="Demo executed quantity" value={Number(stats.volume??0).toFixed(4)}/> <StatCard label="Demo trading fees" value={`$${Number(stats.fees??0).toFixed(2)}`}/><StatCard label="Demo open positions" value={String(stats.positions??0)}/><StatCard label="Demo pending USD deposits" value={`$${Number(stats.demoDeposits??0).toFixed(2)}`}/><StatCard label="Demo pending USD withdrawals" value={`$${Number(stats.demoWithdrawals??0).toFixed(2)}`}/><StatCard label="Real pending USD deposits" value={`$${Number(stats.realDeposits??0).toFixed(2)}`}/><StatCard label="Real pending USD withdrawals" value={`$${Number(stats.realWithdrawals??0).toFixed(2)}`}/></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2">
    <section className="card p-5"><h2 className="font-bold">Funding queue</h2>{funds.length?funds.map(f=><div key={f.id} className="border-b border-white/10 py-4"><div className="flex flex-wrap justify-between gap-2"><span className="break-all">{f.user.email} · {f.accountMode}</span><span>{f.type} {Number(f.amount).toLocaleString()} {f.currency}</span></div><small className="muted break-all">{f.id} · {f.paymentMethod?.name||f.method} · {f.status.replaceAll('_',' ')}</small><details className="mt-2"><summary className="min-h-11 cursor-pointer py-2 text-sm gold">Submission evidence and review note</summary><dl className="grid gap-2 break-words text-xs sm:grid-cols-2"><div><dt className="muted">Transaction reference</dt><dd>{f.transactionReference||'Not provided'}</dd></div><div><dt className="muted">Reference details</dt><dd>{f.referenceInfo||'Not provided'}</dd></div><div><dt className="muted">Sender</dt><dd>{f.senderInfo||'Not provided'}</dd></div><div><dt className="muted">Destination</dt><dd>{f.destinationInfo||'Not provided'}</dd></div><div><dt className="muted">Beneficiary</dt><dd>{f.beneficiaryInfo||'Not provided'}</dd></div><div><dt className="muted">Network</dt><dd>{f.network||'Not provided'}</dd></div><div className="sm:col-span-2"><dt className="muted">User note</dt><dd>{f.note||'Not provided'}</dd></div></dl><label className="mt-3 block text-xs muted">Admin note<input className="input mt-1 min-h-11" value={fundingNotes[f.id]||''} maxLength={500} onChange={event=>setFundingNotes(current=>({...current,[f.id]:event.target.value}))}/></label></details><div className="mt-2 flex flex-wrap gap-2"><button className="btn min-h-11 bg-profit px-4 text-black" onClick={()=>review(f.id,'APPROVED',fundingNotes[f.id]||'')}>Approve</button><button className="btn min-h-11 bg-loss px-4" onClick={()=>review(f.id,'REJECTED',fundingNotes[f.id]||'')}>Reject</button></div></div>):<p className="mt-4 muted">Queue is empty.</p>}</section>
  <section className="card p-5"><h2 className="font-bold">Users</h2><div className="mt-3 max-h-[520px] overflow-auto">{users.map(u=><div key={u.id} className="border-b border-white/10 py-3"><div className="flex flex-wrap justify-between gap-2"><span>{u.email}</span><span className="muted">{u.role} · {u.accountMode} · {u.kycStatus}</span></div><div className="mt-2 flex flex-wrap gap-2"><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'status',u.status==='ACTIVE'?'FROZEN':'ACTIVE')}>{u.status==='ACTIVE'?'Freeze':'Unfreeze'}</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'kycStatus','APPROVED')}>Approve KYC</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'kycStatus','REJECTED')}>Reject KYC</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'kycStatus','NEEDS_CHANGES')}>Request KYC changes</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'role',u.role==='ADMIN'?'USER':'ADMIN')}>{u.role==='ADMIN'?'Make user':'Make admin'}</button><button className="btn bg-white/5" type="button" aria-expanded={expandedLoginUser===u.id} onClick={()=>void toggleLoginHistory(u.id)}>{expandedLoginUser===u.id?'Hide login history':'Login history'}</button></div>{expandedLoginUser===u.id&&<div className="mt-3 rounded-md border border-white/10 bg-black/10 p-3" aria-label={`Login history for ${u.email}`}>{loginHistory[u.id]?.loading?<p className="muted text-sm" role="status">Loading login history…</p>:loginHistory[u.id]?.error?<p className="text-sm text-loss" role="alert">{loginHistory[u.id].error}</p>:loginHistory[u.id]?.events.length?loginHistory[u.id].events.map(event=><div className="grid gap-1 border-b border-white/10 py-2 text-xs sm:grid-cols-2" key={event.id}><span>{new Date(event.createdAt).toLocaleString()} · {event.action.replace('LOGIN_','')}</span><span>IP: {event.metadata?.clientIp||'Not available'} · {event.metadata?.authMethod||'credentials'}</span><span className="break-all muted sm:col-span-2">{event.metadata?.userAgent||'User agent not available'}</span></div>):<p className="muted text-sm">No recorded login attempts.</p>}</div>}</div>)}</div></section>
    <section className="card p-5"><h2 className="font-bold">Open positions</h2>{positions.length?positions.map(p=><div key={p.id} className="flex items-center justify-between gap-3 border-b border-white/10 py-3"><span>{p.user.email} · {p.accountMode} · {p.instrument.symbol} · {p.side}</span><button className="btn bg-loss" disabled={p.accountMode==='REAL'} title={p.accountMode==='REAL'?'External REAL settlement is not connected.':'Close simulated position'} onClick={()=>forceClose(p.id)}>{p.accountMode==='REAL'?'External close unavailable':'Force close DEMO'}</button></div>):<p className="mt-4 muted">No open positions.</p>}</section>
  <section className="card p-5"><h2 className="font-bold">Instrument management</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className="input" placeholder="Symbol" value={newInstrument.symbol} onChange={e=>setNewInstrument({...newInstrument,symbol:e.target.value.toUpperCase()})}/><input className="input" placeholder="Name" value={newInstrument.name} onChange={e=>setNewInstrument({...newInstrument,name:e.target.value})}/><input className="input" placeholder="Base asset" value={newInstrument.baseAsset} onChange={e=>setNewInstrument({...newInstrument,baseAsset:e.target.value.toUpperCase()})}/><input className="input" placeholder="Quote asset" value={newInstrument.quoteAsset} onChange={e=>setNewInstrument({...newInstrument,quoteAsset:e.target.value.toUpperCase()})}/><input className="input" type="number" placeholder="Price" value={newInstrument.price} onChange={e=>setNewInstrument({...newInstrument,price:e.target.value})}/><input className="input" type="number" placeholder="Leverage" value={newInstrument.leverage} onChange={e=>setNewInstrument({...newInstrument,leverage:e.target.value})}/><input className="input" type="number" step="0.000001" placeholder="Maker fee" value={newInstrument.makerFee} onChange={e=>setNewInstrument({...newInstrument,makerFee:e.target.value})}/><input className="input" type="number" step="0.000001" placeholder="Taker fee" value={newInstrument.takerFee} onChange={e=>setNewInstrument({...newInstrument,takerFee:e.target.value})}/></div><button className="btn mt-3 bg-gold text-black" onClick={createInstrument}>Add instrument</button><div className="mt-5 space-y-2">{instruments.map(i=><div key={i.id} className="rounded-xl bg-white/5 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-bold">{i.symbol} · {Number(i.price).toLocaleString()}</span><button className="btn bg-white/5" onClick={()=>instrumentPatch(i.id,{enabled:!i.enabled})}>{i.enabled?'Disable':'Enable'}</button></div><div className="mt-2 grid grid-cols-2 gap-2"><input className="input" type="number" value={i.price} onChange={e=>setInstruments(xs=>xs.map(x=>x.id===i.id?{...x,price:Number(e.target.value)}:x))}/><input className="input" type="number" value={i.leverage} onChange={e=>setInstruments(xs=>xs.map(x=>x.id===i.id?{...x,leverage:Number(e.target.value)}:x))}/></div><button className="btn mt-2 bg-white/5" onClick={()=>instrumentPatch(i.id,{price:Number(i.price),leverage:Number(i.leverage)})}>Save market settings</button></div>)}</div></section>
  <section className="card p-5"><h2 className="font-bold">System settings</h2>{settings.length?settings.map(x=><div key={x.key} className="flex items-center gap-3 border-b border-white/10 py-3"><span className="min-w-40 text-sm">{x.key}</span><input className="input" defaultValue={x.value} onBlur={e=>saveSetting(x.key,e.currentTarget.value)}/></div>):<p className="mt-4 muted">No settings yet.</p>}</section>
  <section className="card p-5 lg:col-span-2"><h2 className="font-bold">Audit and notification events</h2><div className="mt-3 max-h-80 overflow-auto">{audit.length?audit.map(x=><div key={x.id} className="border-b border-white/10 py-2 text-xs"><span>{new Date(x.createdAt).toLocaleString()}</span> · <span className="gold">{x.action}</span> · {x.entity} {x.summary?`· ${x.summary}`:''}</div>):<p className="muted">No recorded events yet.</p>}</div></section>
 </div></main></>
}
