'use client';

import {useEffect,useState} from 'react';
import {Check,Clock3,LockKeyhole,ShieldCheck} from 'lucide-react';
import Nav from '@/components/Nav';

const tiers=[
 {label:'TIER 1',title:'Demo access',description:'Explore simulated markets, portfolio data, and basic account tools.',features:['Demo account balance','Market charts','Watchlists','Profile completion']},
 {label:'TIER 2',title:'Verification preparation',description:'Prepare identity and account details for review. No regulated access is implied.',features:['Advanced research tools','Alerts','Review progress','Admin status visibility']},
 {label:'TIER 3',title:'Identity review complete',description:'Your submitted profile and identity document have been approved. This does not enable real-money services.',features:['Approved identity document','Administrator review recorded','External execution is unavailable','Demo trading remains simulated']},
];

export default function AccountTierPanel(){
 const [data,setData]=useState<{tier:string;progress:number;verified:boolean;kycStatus:string;documents:number;accountMode:string}|null>(null);const [error,setError]=useState('');
 useEffect(()=>{void fetch('/api/profile').then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load account status.');setData(result);}).catch(exception=>setError(exception instanceof Error?exception.message:'Unable to load account status.'));},[]);
 return <><Nav/><main className="account-page"><header className="account-heading"><div><span className="account-kicker">Account access</span><h1>Tier and verification</h1><p>Transparent account readiness, current review status, and explicit restrictions.</p></div><span className="status-pill mode-demo">{data?.accountMode||'DEMO'} ACCOUNT</span></header>{error&&<p className="text-sm text-loss" role="alert">{error}</p>}<div className="mt-4 grid gap-4 lg:grid-cols-3">{tiers.map(tier=>{const current=tier.label===data?.tier;const complete=tier.label==='TIER 1'&&data?.tier==='TIER 1';return <article className={`card p-5 ${current?'border-gold/50':''}`} key={tier.label}><div className="flex items-center justify-between"><h2 className="font-bold">{tier.label}</h2>{current&&<ShieldCheck size={18} className="gold"/>}</div><h3 className="mt-4 text-lg font-semibold">{tier.title}</h3><p className="mt-2 text-sm leading-6 muted">{tier.description}</p><ul className="mt-4 space-y-2">{tier.features.map(feature=><li className="flex items-start gap-2 text-sm" key={feature}><Check size={15} className="mt-0.5 shrink-0 gold"/>{feature}</li>)}</ul><div className="mt-5 border-t border-white/10 pt-4"><span className="muted text-xs">Current status</span><p className="mt-1 text-sm">{current?`${data?.progress??0}% complete · ${data?.kycStatus||'Not started'}`:'Not currently assigned'}</p></div>{tier.label==='TIER 3'&&<p className="mt-3 text-xs leading-5 muted">Eligibility is not implied until independent legal and licensing review is completed.</p>}</article>})}</div><section className="account-panel card p-5 mt-4"><div className="account-panel-title"><div><h2>Verification path</h2><p className="account-panel-subtitle">No identity document is exposed publicly.</p></div><LockKeyhole size={18} className="gold"/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/5 p-4"><Clock3 size={17} className="gold"/><p className="mt-2 text-sm font-semibold">Submit</p><p className="mt-1 text-xs muted">Provide identity details and secure document artifacts.</p></div><div className="rounded-xl bg-white/5 p-4"><ShieldCheck size={17} className="gold"/><p className="mt-2 text-sm font-semibold">Review</p><p className="mt-1 text-xs muted">An administrator reviews the record and records notes.</p></div><div className="rounded-xl bg-white/5 p-4"><Check size={17} className="gold"/><p className="mt-2 text-sm font-semibold">Approve</p><p className="mt-1 text-xs muted">Approval is issued only after the configured verification policy passes.</p></div></div><p className="mt-4 text-xs leading-5 muted">A real-account tier does not grant legal or regulated trading eligibility. Any future external provider or financial integration must be explicitly configured and documented.</p></section></main></>;
}
