'use client';

import Image from 'next/image';
import Link from 'next/link';
import {useCallback,useEffect,useState,type ReactNode} from 'react';
import {Activity,ArrowRight,ArrowUpRight,BadgeCheck,Bell,Building2,CircleDollarSign,Clock3,Eye,Landmark,LineChart,LoaderCircle,ShieldCheck,Sparkles,TrendingUp,UserRound,WalletCards,X} from 'lucide-react';
import Nav from '@/components/Nav';
import {useQuery} from '@tanstack/react-query';
import {useLocale} from '@/lib/i18n-context';

type DashboardData={accountMode:'DEMO'|'REAL';cash:string|null;financialDataAvailable:boolean;positionValue:string;invested:string;unrealized:string;portfolioValue:string|null;openOrders:number;activePositions:number;activity:Array<{id:string;category:string;action:string;timestamp:string;asset:string;amount:string;status:string;source:string;pnl:string|null;adminInitiated:boolean;link:string}>;orders:Array<{id:string;side:string;type:string;status:string;accountMode:'DEMO'|'REAL';quantity:string;filledQuantity:string;price:string|null;createdAt:string;instrument:{symbol:string;name:string}}>;positions:Array<{id:string;side:string;quantity:string;entryPrice:string;instrument:{symbol:string;name:string;price:string}}> ;investments:Array<{id:string;status:string;amount:string;opportunity:{title:string;category:string;riskLevel:string;assetSymbol:string|null;targetReturnPercent:string|null;durationDays:number}}> ;notifications:Array<{id:string;type:string;title:string;message:string;isRead:boolean;createdAt:string;actionUrl:string|null}>;profile:{id:string;email:string|null;name:string|null;hasAvatar:boolean;role:'USER'|'ADMIN';status:string|null;accountMode:'DEMO'|'REAL';kycStatus:string|null;verifiedAt:string|null;verifiedChannel:string|null;phoneVerified:boolean;phone:string|null;country:string|null;createdAt:string|null;tier:string;progress:number;eligibleForRealTrading:boolean;verified:boolean;withdrawalEnabled?:boolean;accountRestricted?:boolean;restrictionReason?:string|null};marketInstruments:Array<{id:string;symbol:string;name:string;price:number;changePercent:number;updatedAt:string}>};

type MarketQuote={asset:{id:string;name:string;currency:string};price:number;changePercent:number;updatedAt:string;isStale?:boolean;staleReason?:string};

const money=(locale:string,value:string|null)=>value===null?'—':new Intl.NumberFormat(locale,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value));
const signed=(locale:string,value:string)=>{const n=Number(value);return `${n>=0?'+':''}${money(locale,value)}`};

export default function DashboardExperience(){
  const {locale,translate}=useLocale();
  const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [showAllActivity,setShowAllActivity]=useState(false);const [showOrders,setShowOrders]=useState(false);const [avatarUrl,setAvatarUrl]=useState('');
  const load=useCallback(async()=>{try{const response=await fetch('/api/dashboard',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||translate('dashboardError'));setData(result);setError('');setAvatarUrl('');if(result.profile.hasAvatar){try{const avatar=await fetch('/api/profile/avatar',{cache:'no-store'});if(avatar.ok){const signed=await avatar.json();setAvatarUrl(signed.url)}}catch{}}}catch(exception){setError(exception instanceof Error?exception.message:translate('dashboardError'));}finally{setLoading(false)}},[translate]);
  useEffect(()=>{void load()},[load]);
  const marketQuery=useQuery({queryKey:['dashboard-market',data?.marketInstruments.map(i=>i.symbol).join(',')],queryFn:async()=>{const symbols=data?.marketInstruments.map(i=>i.symbol)||[];if(!symbols.length)return {quotes:[]};const response=await fetch(`/api/live-markets?symbols=${encodeURIComponent(symbols.join(','))}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Market feed unavailable.');return body as {quotes:Array<MarketQuote|{asset:{id:string};error:string}>}},enabled:!!data&&data.marketInstruments.length>0,refetchInterval:30_000});
  if(loading&&!data)return <><Nav/><main className="account-page dashboard-loading"><LoaderCircle size={24} className="gold animate-spin"/><p>{translate('loadingWorkspace')}</p></main></>;
  if(error&&!data)return <><Nav/><main className="account-page"><div className="account-callout" role="alert"><span>{error}</span><button type="button" className="text-link" onClick={()=>void load()}>{translate('retry')}</button></div></main></>;
  if(!data)return null;
  const profile=data.profile;const mode=data.accountMode;const verified=profile.verified;const totalPnl=Number(data.unrealized)+Number(data.invested)>0?Number(data.unrealized):0;const isDemo=mode==='DEMO';const firstName=profile.name?.trim().split(/\s+/)[0]||translate('account');
  return <><Nav/><main className="account-page dashboard-page">
    <header className="dashboard-hero"><div className="dashboard-greeting"><div className="profile-avatar-wrap">{avatarUrl?<Image src={avatarUrl} alt="" width={56} height={56} className="profile-avatar" unoptimized/>:<span className="profile-avatar-fallback"><UserRound size={22}/></span>}<span className={`profile-verified ${verified?'is-verified':''}`}>{verified?<BadgeCheck size={14}/>:<X size={13}/>}</span></div><div><span className="account-kicker">{isDemo?translate('demoAccount') : translate('realAccount')} · {profile.tier}</span><h1>{translate('hello',{name:firstName})}</h1><p><b>{profile.name||translate('unavailable')}</b>{profile.email&&<> · {profile.email}</>}<br/>{verified?translate('verifiedAccountLine',{channel:profile.verifiedChannel||translate('account')}):translate('verificationIncomplete')} · {profile.status?.toLowerCase()||translate('unavailable')}</p></div></div><div className="dashboard-hero-actions"><Link href="/notifications" className="icon-action" aria-label={translate('openNotifications')}><Bell size={16}/>{data.notifications.some(n=>!n.isRead)&&<span className="notification-count">{data.notifications.filter(n=>!n.isRead).length}</span>}</Link><Link href="/settings" className="button-secondary"><UserRound size={14}/>Edit Profile</Link></div></header>
    <section className="dashboard-profile-panel card" aria-label={translate('profileLabel')}><div><span>{translate('name')}</span><b>{profile.name||translate('unavailable')}</b></div><div><span>{translate('emailAddress')}</span><b>{profile.email||translate('unavailable')}</b></div><div><span>{translate('phone')}</span><b>{profile.phone||translate('unavailable')}</b></div><div><span>{translate('country')}</span><b>{profile.country||translate('unavailable')}</b></div><div><span>{translate('accountStatus')}</span><b>{profile.status||translate('unavailable')}</b></div><div><span>{translate('accountTier')}</span><b>{profile.tier}</b></div><div><span>{translate('verificationStatus')}</span><b className={verified?'text-profit':'text-loss'}>{verified?translate('verified'):profile.kycStatus||translate('unavailable')}</b></div><div><span>{translate('mode')}</span><b>{mode}</b></div></section>
    {!isDemo&&<section className="dashboard-real-state"><ShieldCheck size={18}/><div><b>{translate('realAccount')}</b><p>{data.financialDataAvailable?translate('realUnavailable'):'Real account data is currently unavailable. No demo values are shown.'}</p></div></section>}
    <section className="dashboard-metrics">
      <Metric icon={CircleDollarSign} label={translate('portfolioValue')} value={money(locale,data.portfolioValue)} detail={isDemo?translate('cashPlus'):translate('postedCash')} tone="gold"/>
      <Metric icon={WalletCards} label={translate('availableCash')} value={money(locale,data.cash)} detail={translate('buyPower')} tone="green"/>
      <Metric icon={Building2} label={translate('investedAmount')} value={isDemo?money(locale,data.invested):translate('unavailable')} detail={isDemo?translate('reservedDemo'):translate('recordedRequests')} tone="blue"/>
      <Metric icon={TrendingUp} label={translate('dailyPL')} value={isDemo?signed(locale,data.unrealized):translate('unavailable')} detail={isDemo?translate('simulatedPosition'):translate('noExternalValuation')} tone={Number(data.unrealized)>=0?'green':'red'}/>
      <Metric icon={Sparkles} label={translate('totalPL')} value={isDemo?signed(locale,String(totalPnl)):translate('unavailable')} detail={isDemo?translate('recordedSimulated'):translate('notIndependentlyValued')} tone={totalPnl>=0?'green':'red'}/>
      <Metric icon={Landmark} label={translate('openPositions')} value={String(data.activePositions)} detail={isDemo?translate('simulatedPositions'):translate('externalPositionsUnavailable')} tone="gold"/>
    </section>
    <div className="dashboard-grid">
      <section className="dashboard-panel card"><Header icon={LineChart} title={translate('marketOverview')} subtitle={isDemo?translate('simulatedInternal'):translate('externalMarket')} link="/markets" action={<StatusDot stale={false}/>} openLabel={translate('open')}/><div className="market-overview-list">{data.marketInstruments.slice(0,6).map(item=>{const quote=marketQuery.data?.quotes.find(q=>!('error' in q)&&q.asset.id===item.symbol);const liveQuote=quote&&!('error' in quote)?quote:undefined;return <Link href={`/markets?symbol=${item.symbol}`} className="market-row" key={item.symbol}><span><b>{item.symbol}</b><small>{item.name}</small></span>{liveQuote&&Number.isFinite(liveQuote.price)?<><strong>{formatPrice(locale,liveQuote.price)}</strong><em className={liveQuote.changePercent>=0?'text-profit':'text-loss'}>{formatPercent(locale,liveQuote.changePercent)}</em></>:<span className="market-unavailable">—</span>}</Link>})}</div></section>
      <section className="dashboard-panel card"><Header icon={Activity} title={translate('recentActivity')} subtitle={translate('persistedEvents')} link="/activity" openLabel={translate('open')}/><div className="recent-activity-list">{data.activity.length ? data.activity.slice(0,5).map(item=><Link href={item.link} className="recent-activity-row" key={item.id}><span className={`activity-dot activity-${item.category}`}/><span><b>{item.action}</b><small>{item.asset} · {item.source}</small></span><span><em>{item.status}</em><strong className={item.pnl&&Number(item.pnl)<0?'text-loss':item.pnl?'text-profit':''}>{item.pnl===null?'':`${Number(item.pnl)>=0?'+':'−'}${money(locale,item.pnl)}`}</strong></span></Link>) : <Empty icon={Activity} title={translate('noActivity')} text={translate('activityDescription')}/>}</div></section>
      <section className="dashboard-panel card"><Header icon={Clock3} title={translate('openDemoOrders')} subtitle={isDemo?translate('pendingSimulated'):translate('noExecutionOrders')} link="/orders" action={<span className="status-pill mode-demo">{data.openOrders} {translate('statusOpen')}</span>} openLabel={translate('open')}/>{isDemo ? (data.orders.filter(o => o.status === 'OPEN').length ? <div className="order-mini-list">{data.orders.filter(o => o.status === 'OPEN').slice(0, 4).map(order=><div className="order-mini-row" key={order.id}><span className={order.side === 'BUY' ? 'buy' : 'sell'}>{order.side}</span><div><b>{order.instrument.symbol}</b><small>{order.type} · {Number(order.quantity).toLocaleString(locale)}</small></div><em>{order.price ? money(locale, order.price) : translate('market')}</em><Link href={`/orders#${order.id}`} aria-label={translate('openOrder', {symbol: order.instrument.symbol})}><ArrowRight size={14}/></Link></div>)}</div> : <Empty icon={Clock3} title={translate('noOpenOrders')} text={translate('submitDemo')}/>) : <div className="real-unavailable"><ShieldCheck size={18}/><p>{translate('realUnavailable')}</p><Link href="/orders" className="text-link">{translate('viewRecordedOrders')} <ArrowUpRight size={13}/></Link></div>}</section>
      <section className="dashboard-panel card">
        <Header icon={Building2} title={translate('investments')} subtitle={translate('lifecycle')} link="/investments" openLabel={translate('open')}/>
        <div className="investment-mini-list">
          {data.investments.length ? data.investments.slice(0,5).map(item=><article key={item.id}><span className={`investment-status ${item.status.toLowerCase()}`}><b>{item.opportunity.title}</b><small>{item.opportunity.category} · {item.opportunity.riskLevel}</small></span><div><b>{money(locale,item.amount)}</b><small>{item.status.replaceAll('_',' ')}</small></div></article>) : <Empty icon={Building2} title={translate('noInvestmentRequests')} text={translate('availableOpportunities')}/>} 
        </div>
      </section>
      <section className="dashboard-panel card dashboard-notifications">
        <Header icon={Bell} title={translate('notificationsTitle')} subtitle={translate('recentAlerts')} link="/notifications" openLabel={translate('open')}/>
        <div className="notification-mini-list">
          {data.notifications.length ? data.notifications.slice(0,5).map(item=><Link href={item.actionUrl||'/notifications'} key={item.id} className={`notification-mini ${item.isRead?'is-read':''}`}><span className="notification-mini-icon"><Bell size={14}/></span><span><b>{item.title}</b><small>{item.message}</small></span><em>{new Date(item.createdAt).toLocaleDateString(locale)}</em></Link>) : <Empty icon={Bell} title={translate('noNotifications')} text={translate('noNotificationsDescription')}/>} 
        </div>
      </section>
      <section className="dashboard-panel card dashboard-quick"><Header icon={Sparkles} title={translate('quickActions')} subtitle={translate('moveNext')} link="/trade" openLabel={translate('open')}/><div className="quick-grid"><Quick href="/trade" icon={TrendingUp} label={translate('tradeDemo')} detail={translate('openSimulatedOrder')}/><Quick href="/portfolio" icon={Landmark} label={translate('portfolioAction')} detail={translate('reviewPositions')}/><Quick href="/wallet" icon={WalletCards} label={translate('walletAction')} detail={translate('fundingReceipts')}/><Quick href="/kyc" icon={ShieldCheck} label={translate('verificationAction')} detail={translate('reviewKyc')}/><Quick href="/support" icon={Activity} label={translate('supportAction')} detail={translate('openSupport')}/><Quick href="/settings" icon={Eye} label={translate('settingsAction')} detail={translate('profileSecurity')}/></div></section>
    </div>
    <section className="dashboard-support-strip"><div><span className="support-icon"><Activity size={18}/></span><div><b>{translate('needHelp')}</b><small>{translate('supportAvailable')}</small></div></div><Link href="/support" className="button-secondary">{translate('openSupportButton')} <ArrowUpRight size={14}/></Link></section>
  </main></>;
}

function Metric({icon:Icon,label,value,detail,tone}:{icon:typeof CircleDollarSign;label:string;value:string;detail:string;tone:string}){return <article className="dashboard-metric"><span className={`metric-icon metric-${tone}`}><Icon size={16}/></span><div><span>{label}</span><b>{value}</b><small>{detail}</small></div></article>}
function Header({icon:Icon,title,subtitle,link,action,openLabel}:{icon:typeof Activity;title:string;subtitle:string;link?:string;action?:ReactNode;openLabel?:string}){return <div className="dashboard-panel-title"><div><h2><Icon size={15} className="gold"/>{title}</h2><p>{subtitle}</p></div><div>{action}{link&&<Link href={link} className="text-link">{openLabel||'Open'} <ArrowUpRight size={12}/></Link>}</div></div>}
function Quick({href,icon:Icon,label,detail}:{href:string;icon:typeof Activity;label:string;detail:string}){return <Link href={href} className="quick-action"><span><Icon size={16}/></span><div><b>{label}</b><small>{detail}</small></div><ArrowUpRight size={13}/></Link>}
function Empty({icon:Icon,title,text}:{icon:typeof Activity;title:string;text:string}){return <div className="dashboard-empty"><Icon size={18}/><div><b>{title}</b><p>{text}</p></div></div>}
function StatusDot({stale}:{stale:boolean}){return <span className={`status-dot ${stale?'is-stale':''}`}/>} 
function formatPrice(locale:string,value:number){return new Intl.NumberFormat(locale,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(value)}
function formatPercent(locale:string,value:number){return `${value>=0?'+':''}${value.toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2})}%`}
