'use client';

import {FormEvent,useCallback,useEffect,useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {RefreshCw} from 'lucide-react';
import Nav from '@/components/Nav';

type Position={id:string;side:string;quantity:string;entryPrice:string;currentPrice:string|null;marketValue:string|null;unrealizedPnl:string|null;openedAt:string;instrument:{symbol:string;name:string;price:string}};
type Snapshot={snapshotBucket:string;totalValue:string};
type Portfolio={accountMode:'DEMO'|'REAL';cashBalance:string;positionValue:string;investmentValue:string;totalValue:string;realizedPnl:string|null;unrealizedPnl:string|null;totalPnl:string|null;returnPercent:string|null;dailyPnl:string|null;positions:Position[];investments:Array<{id:string;status:string;amount:string;opportunity:{title:string}}>;allocations:Array<{symbol:string;value:string;percentage:string}>;topGainers:Position[];topLosers:Position[];performance:Snapshot[];marketDataMode:string;externalValuationAvailable:boolean};

function money(value:string|number|null|undefined){return value===null||value===undefined?'—':`$${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function signed(value:string|number|null|undefined){if(value===null||value===undefined)return 'Unavailable';const number=Number(value);return `${number>=0?'+':''}${money(number)}`;}

export default function PortfolioExperience(){
 const [data,setData]=useState<Portfolio|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [resetOpen,setResetOpen]=useState(false);const [resetConfirmation,setResetConfirmation]=useState('');const [resetBusy,setResetBusy]=useState(false);
 const load=useCallback(async(showLoading=false)=>{if(showLoading)setLoading(true);try{const response=await fetch('/api/portfolio',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load portfolio.');setData(result);setError('');}catch(exception){setError(exception instanceof Error?exception.message:'Unable to load portfolio.');}finally{if(showLoading)setLoading(false);}},[]);
 useEffect(()=>{void load(true);},[load]);
 const positive=Number(data?.totalPnl||0)>=0;

 async function resetDemo(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(resetBusy||resetConfirmation!=='RESET DEMO ACCOUNT')return;
  setResetBusy(true);setError('');setNotice('');
  try{
   const response=await fetch('/api/account/demo-reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirmation:resetConfirmation})});
   const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to reset DEMO account.');
   setNotice(`DEMO portfolio reset to ${money(result.balance)}. Historical ledger and audit entries were retained.`);setResetConfirmation('');setResetOpen(false);await load();
  }catch(exception){setError(exception instanceof Error?exception.message:'Unable to reset DEMO account.');}
  finally{setResetBusy(false);}
 }

 return <><Nav/><main className="account-page portfolio-page">
  <header className="account-heading"><div><span className="account-kicker">ACCOUNT OVERVIEW</span><h1>Portfolio</h1><p>Cash, positions, investments, and recorded performance for the selected mode.</p></div><div className="flex items-center gap-2"><span className={`status-pill ${data?.accountMode==='REAL'?'mode-real':'mode-demo'}`}>{data?`${data.accountMode} ACCOUNT`:'Loading'}</span><button className="icon-action" type="button" aria-label="Refresh portfolio" onClick={()=>void load(true)}><RefreshCw size={15}/></button></div></header>
  {data?.accountMode==='REAL'&&<div className="account-callout mb-4"><span>REAL valuation is not connected to an external broker. Displayed account value includes recorded cash only; external positions and investment values are not independently verified.</span></div>}
    {notice&&<p className="mb-3 text-sm text-profit" role="status">{notice}</p>}{error&&<div className="account-callout mb-4" role="alert"><span>{error}</span><button type="button" className="text-link" onClick={()=>void load(true)}>Retry</button></div>}
  {loading&&!data?<p className="account-empty" role="status">Loading portfolio…</p>:data&&<>
   <section className="portfolio-summary"><div className="portfolio-total"><span>Total recorded value</span><strong>{money(data.totalValue)}</strong><small>{data.accountMode==='DEMO'?'Simulated cash + simulated holdings':'Recorded cash only'}</small></div><div className="portfolio-metric"><span>Available cash</span><b>{money(data.cashBalance)}</b></div><div className="portfolio-metric"><span>Position value</span><b>{data.accountMode==='DEMO'?money(data.positionValue):'Not valued'}</b></div><div className="portfolio-metric"><span>Reserved investments</span><b>{data.accountMode==='DEMO'?money(data.investmentValue):'Not valued'}</b></div></section>
    {data.accountMode==='DEMO'&&<section className="demo-reset-control"><div><b>Reset simulated portfolio</b><p>Resets DEMO cash to $5,000.00, closes open simulated positions, cancels open orders and unsettled DEMO investment requests. Completed investments must be settled first. Historical ledger and audit records are retained.</p></div>{!resetOpen?<button type="button" className="button-secondary" onClick={()=>setResetOpen(true)}>Reset DEMO</button>:<form onSubmit={event=>void resetDemo(event)}><label className="account-label">Type RESET DEMO ACCOUNT to confirm<input className="input" autoComplete="off" value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)}/></label><div className="flex flex-wrap gap-2"><button className="btn bg-loss" disabled={resetBusy||resetConfirmation!=='RESET DEMO ACCOUNT'}>{resetBusy?'Resetting…':'Confirm DEMO reset'}</button><button className="btn bg-white/5" type="button" onClick={()=>{setResetOpen(false);setResetConfirmation('');}}>Cancel</button></div></form>}</section>}
  <section className="portfolio-metrics-grid"><article><span>Total P/L</span><b className={positive?'text-profit':'text-loss'}>{signed(data.totalPnl)}</b></article><article><span>Realized P/L</span><b>{signed(data.realizedPnl)}</b></article><article><span>Unrealized P/L</span><b>{signed(data.unrealizedPnl)}</b></article><article><span>Daily P/L</span><b>{signed(data.dailyPnl)}</b></article><article><span>Return since demo allocation</span><b>{data.returnPercent===null?'Unavailable':`${Number(data.returnPercent)>=0?'+':''}${Number(data.returnPercent).toFixed(2)}%`}</b></article></section>
   <div className="portfolio-content-grid">
    <section className="account-panel card p-5"><div className="account-panel-title"><div><h2>Performance history</h2><p className="account-panel-subtitle">Recorded snapshots · captured at most every 15 minutes</p></div><span className="muted text-xs">{data.marketDataMode}</span></div>{data.performance.length>1?<div className="portfolio-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.performance}><defs><linearGradient id="portfolioValueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d5b15d" stopOpacity={0.3}/><stop offset="100%" stopColor="#d5b15d" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(218,225,216,.08)" vertical={false}/><XAxis dataKey="snapshotBucket" tickFormatter={value=>new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'})} tick={{fill:'#92a096',fontSize:11}} axisLine={false} tickLine={false}/><YAxis width={72} tickFormatter={value=>`$${Number(value).toLocaleString()}`} tick={{fill:'#92a096',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={value=>new Date(String(value)).toLocaleString()} formatter={value=>[money(String(value)),'Recorded value']} contentStyle={{background:'#0b1711',border:'1px solid rgba(218,225,216,.16)',borderRadius:4,color:'#f4f7f5'}}/><Area type="monotone" dataKey="totalValue" stroke="#d5b15d" strokeWidth={2} fill="url(#portfolioValueFill)"/></AreaChart></ResponsiveContainer></div>:<p className="account-empty">Performance history appears after multiple portfolio snapshots have been recorded.</p>}</section>
    <section className="account-panel card p-5"><div className="account-panel-title"><div><h2>Allocation</h2><p className="account-panel-subtitle">Current DEMO positions by instrument</p></div></div>{data.accountMode==='DEMO'&&data.allocations.length?<div className="portfolio-allocation">{data.allocations.map(item=><div key={item.symbol}><div><b>{item.symbol}</b><span>{money(item.value)} · {Number(item.percentage).toFixed(1)}%</span></div><i><span style={{width:`${Math.min(100,Number(item.percentage))}%`}}/></i></div>)}</div>:<p className="account-empty">No valued positions in this account mode.</p>}</section>
   </div>
   <section className="account-panel card p-5 mt-4"><div className="account-panel-title"><div><h2>Open positions</h2><p className="account-panel-subtitle">{data.accountMode==='DEMO'?'Current simulated market marks':'External valuation unavailable'}</p></div><span className="muted text-sm">{data.positions.length} open</span></div>{data.positions.length?<div className="portfolio-position-list">{data.positions.map(position=><article key={position.id}><div><b>{position.instrument.symbol}</b><span>{Number(position.quantity).toLocaleString()} units · average entry {money(position.entryPrice)}</span></div><div><b>{position.currentPrice===null?'—':money(position.currentPrice)}</b><span>Market value {money(position.marketValue)}</span></div><b className={Number(position.unrealizedPnl||0)>=0?'text-profit':'text-loss'}>{signed(position.unrealizedPnl)}</b></article>)}</div>:<p className="account-empty">No open positions.</p>}</section>
   <section className="account-panel card p-5 mt-4"><div className="account-panel-title"><div><h2>Top movers</h2><p className="account-panel-subtitle">Open DEMO positions only</p></div></div>{data.accountMode==='DEMO'&&data.positions.length?<div className="portfolio-movers"><div><b>Top gainers</b>{data.topGainers.length?data.topGainers.map(position=><span key={position.id}>{position.instrument.symbol}<strong className="text-profit">{signed(position.unrealizedPnl)}</strong></span>):<small>None yet</small>}</div><div><b>Top decliners</b>{data.topLosers.length?data.topLosers.map(position=><span key={position.id}>{position.instrument.symbol}<strong className="text-loss">{signed(position.unrealizedPnl)}</strong></span>):<small>None yet</small>}</div></div>:<p className="account-empty">No simulated positions to rank.</p>}</section>
   <section className="account-panel card p-5 mt-4"><div className="account-panel-title"><div><h2>Investments</h2><p className="account-panel-subtitle">Request amounts are not projected returns.</p></div></div>{data.investments.length?<div className="portfolio-position-list">{data.investments.map(item=><article key={item.id}><div><b>{item.opportunity.title}</b><span>{item.status.replaceAll('_',' ')}</span></div><b>{money(item.amount)}</b></article>)}</div>:<p className="account-empty">No investment activity.</p>}</section>
  </>}
 </main></>;
}