import InfoPage from '@/components/InfoPage';

export default function RiskDisclosure(){
  return <InfoPage eyebrow="Important information" title="Risk disclosure" lead="Understand the limits of this demo and the risks associated with investing and trading." sections={[
    {title:'Investment risk',content:<p>Investing and trading involve risk. The value of investments can rise or fall, and you may lose some or all of the capital you invest. Leverage can magnify both gains and losses. Consider whether a product is appropriate for your circumstances and seek independent advice where needed.</p>},
    {title:'Simulated market data',content:<p>Prices and order-book views in Aurevia Invest are generated by an internal simulation. They are not live quotes, exchange data, executable prices, or a representation of actual market conditions. Simulated performance does not predict future outcomes.</p>},
    {title:'Demo balances and funding',content:<p>Balances, deposits, withdrawals, positions, fees, and executions are records in a demo application. No bank, card, custody, blockchain, or external execution provider is connected. A displayed demo balance is not cash held for you.</p>},
    {title:'Information, not advice',content:<p>Platform content is general information for product exploration and education. It is not personalized investment, legal, tax, or financial advice, and it is not an offer or recommendation to buy or sell an instrument.</p>},
  ]}/>;
}